### PR TITLE
Add additional buttons to skip forward/back a fixed amount

### PR DESCRIPTION
**Pull request by AlpyneDreams**
This is what the chapter skip buttons used to do in the original modern. These buttons are added in addition to the chapter skip buttons so you can still skip around in a file with no chapters.

Preview:
preview
 
Left Mouse Button skips 5 seconds
Shift+LMB can skip 1 frame
RMB can skip 1 minute

These could be made optional with a config setting.

### CODE REVIEW

**Comment by cyl0** [comment]
Looks good, though I think that this should definitely be added as an option rather than a default behaviour as this script aims to mirror the functionality of the default MPV OSC.

**Comment by AlpyneDreams** [comment]
For sure, I will add a config option.

**Comment by AlpyneDreams** [comment]
I'll also make the skip amount configurable

**Comment by AlpyneDreams** [comment]
Done!

Last questions are:
- Do we want to enable them by default (imo I don't see why not, but it's your call)
- Should the button icons have numbers by default (supported for 5, 10, 30). I think the numbers are kind of small when not in fullscreen.

**Comment by cyl0** [comment]
If that's the case then sure, we'lll have it enabled by default. 
As for the numbers, I think it would be better to keep them unless the jump amount has been configured to be something other than 5, 10 or 30. The icon without the number isn't very intuitavie as to what it does, so I think it's better off keeping the number even if it's small.

**Comment by AlpyneDreams** [comment]
Both of those are already the default as of the latest commit so you can go ahead and merge :)

**Comment by cyl0** [comment]
Great, thanks for contributing!

**Pull request merged**
